title: Modeling Mini Fusion Reactors
theme: jekyll-theme-cayman
description: >
  Jonathan Kelley <br>
  North Carolina School of Science and Mathematics <br>
  High School Research in Physics

github:
  "is_project_page": false
